// <auto-generated />
using System;
using MarketService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketService.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    partial class MarketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MarketService.Models.Crypto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Cryptos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentPrice = 42000m,
                            LastUpdated = new DateTime(2026, 3, 8, 0, 15, 53, 26, DateTimeKind.Utc).AddTicks(870),
                            Name = "BitcoinX",
                            Symbol = "BTC-X"
                        },
                        new
                        {
                            Id = 2,
                            CurrentPrice = 2500m,
                            LastUpdated = new DateTime(2026, 3, 8, 0, 15, 53, 26, DateTimeKind.Utc).AddTicks(1127),
                            Name = "EtherZero",
                            Symbol = "ETH-Z"
                        },
                        new
                        {
                            Id = 3,
                            CurrentPrice = 95m,
                            LastUpdated = new DateTime(2026, 3, 8, 0, 15, 53, 26, DateTimeKind.Utc).AddTicks(1129),
                            Name = "SolaFake",
                            Symbol = "SOL-F"
                        },
                        new
                        {
                            Id = 4,
                            CurrentPrice = 0.08m,
                            LastUpdated = new DateTime(2026, 3, 8, 0, 15, 53, 26, DateTimeKind.Utc).AddTicks(1151),
                            Name = "DogeMoon",
                            Symbol = "DOG-M"
                        },
                        new
                        {
                            Id = 5,
                            CurrentPrice = 0.45m,
                            LastUpdated = new DateTime(2026, 3, 8, 0, 15, 53, 26, DateTimeKind.Utc).AddTicks(1189),
                            Name = "CardanoSim",
                            Symbol = "ADA-S"
                        });
                });

            modelBuilder.Entity("MarketService.Models.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CryptoId")
                        .HasColumnType("int");

                    b.Property<string>("CryptoSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CryptoId");

                    b.HasIndex("CryptoSymbol");

                    b.HasIndex("RecordedAt");

                    b.ToTable("PriceHistory");
                });

            modelBuilder.Entity("MarketService.Models.PriceHistory", b =>
                {
                    b.HasOne("MarketService.Models.Crypto", null)
                        .WithMany("History")
                        .HasForeignKey("CryptoId");
                });

            modelBuilder.Entity("MarketService.Models.Crypto", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
